Set owner to avoid hardhat deploy failure
Without the right owner set, we see the following failure. This is
because hardhat-deploy is verifying the owner field still owns the
default proxy admin
```
Error: To change owner/admin, you need to call transferOwnership on DefaultProxyAdmin
    at _deployViaProxy (/Users/jack/wombat-exchange/wombat/node_modules/hardhat-deploy/src/helpers.ts:1487:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployBasePool (/Users/jack/wombat-exchange/wombat/utils/deploy.ts:64:24)
    at async Object.deployFunc [as func] (/Users/jack/wombat-exchange/wombat/deploy/020_HighCovRatioFeePool.ts:22:46)
    at async DeploymentsManager.executeDeployScripts (/Users/jack/wombat-exchange/wombat/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:22)
```