Fix hardhat verify
hardhat verify is failing due to
> Error: Cannot find module '@nomiclabs/hardhat-etherscan/dist/src/resolveEtherscanApiKey'

This turns out to be a versioning problem. So upgrade the following
packages:
> yarn add --dev @nomiclabs/hardhat-etherscan hardhat-etherscan-abi

Then run into another error, but able to resolve following https://github.com/smartcontractkit/hardhat-starter-kit/issues/140
> TypeError: customChains is not iterable

One last error before I can verify. Fixed with `npx hh clean`
uggested by https://github.com/NomicFoundation/hardhat/issues/1117